// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmw45Vstba1YmaI3flro9YxqrW-xJdAjI',
    appId: '1:184985647911:web:f231f8dabe7d2caf984702',
    messagingSenderId: '184985647911',
    projectId: 'flutterdemo-a7e13',
    authDomain: 'flutterdemo-a7e13.firebaseapp.com',
    storageBucket: 'flutterdemo-a7e13.firebasestorage.app',
    measurementId: 'G-KP9N411N7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFf94spbpN0L08tqfT3Ci33GltYOXCcNQ',
    appId: '1:184985647911:android:282b42ba5b3ac869984702',
    messagingSenderId: '184985647911',
    projectId: 'flutterdemo-a7e13',
    storageBucket: 'flutterdemo-a7e13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_mtSfOmWFnuPyYZOUr-M032v8fnCwxRk',
    appId: '1:184985647911:ios:18cc7c31194ebe30984702',
    messagingSenderId: '184985647911',
    projectId: 'flutterdemo-a7e13',
    storageBucket: 'flutterdemo-a7e13.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_mtSfOmWFnuPyYZOUr-M032v8fnCwxRk',
    appId: '1:184985647911:ios:18cc7c31194ebe30984702',
    messagingSenderId: '184985647911',
    projectId: 'flutterdemo-a7e13',
    storageBucket: 'flutterdemo-a7e13.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );
}
